modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory
license = "MIT License"

[[mods]] #mandatory
modId = "silent_series_patchouli" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Silent Series Manual" #mandatory
#displayURL="http://example.com/" #optional
#logoFile="SilentSeriesPatchouli.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors = "TexTrue, TexStudio" #optional
description = '''
Silent Series Manual Book
'''

[[dependencies.silent_series_patchouli]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.silent_series_patchouli]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
